### ISSUE TITLE
Deprecation: fulfillableQuantity

### ISSUE THREAD

**Issue by mattsodomsky** [lightward/mechanic-tasks#105]
![image](https://user-images.githubusercontent.com/1697187/160931720-8f6f4daf-4a87-441e-8d83-f52712a7ea1e.png)

https://shopify.dev/api/admin-graphql/2022-01/objects/FulfillmentOrderLineItem#implements

Need to update these tasks:

1. https://tasks.mechanic.dev/cancel-and-close-unpaid-orders-after-two-days
2. https://tasks.mechanic.dev/auto-tag-orders-that-contain-a-matching-product

**Comment by davidlee9023** [comment]
https://tasks.mechanic.dev/cancel-and-close-unpaid-orders-after-two-days

A task is depending on a deprecated Shopify API
