### ISSUE TITLE
Task Deprecation: Auto-tag orders that are ready to ship

### ISSUE THREAD

**Issue by mattsodomsky** [lightward/mechanic-tasks#180]
https://tasks.mechanic.dev/auto-tag-orders-that-are-ready-to-ship

![image](https://user-images.githubusercontent.com/1697187/206291315-c44aa8c6-ea29-4092-b545-69daf79f19f7.png)

`{% if options.ignore_line_items_not_fulfilled_manually__boolean %}
                  fulfillmentService {
                    id
                  }
                {% endif %}`

**Comment by tekhaus** [comment]
So this one is more interesting. It looks like the fulfillmentService nodes underneath an assignedLocation or an inventoryLevel.location will only return a null when there is no service assigned to the variant. A null service clearly can't have the gid://shopify/FulfillmentService/manual ID that is being checked for in the task.

Additionally, when I assigned a 3rd party fulfillment service to a variant, that does show up in the inventoryLevel.location node, but not in the assignedLocation node.

Not quite sure what this task should be checking to maintain feature parity. Perhaps if a fulfillmentService is non-null at ANY location where the product is stocked, then that would disqualify it from "manual" shipping?

Thoughts? @isaacbowen @mattsodomsky

**Comment by mattsodomsky** [comment]
https://shopify.dev/api/release-notes/2022-07#shipping-and-fulfillment

Hmmm, yeah based on the above link I would have expected we could check for the fulfillmentService to be null on the assignedLocation node

![image](https://user-images.githubusercontent.com/1697187/208145558-9f540a79-b647-47b8-a2f5-782a7d254908.png)

**Comment by mattsodomsky** [comment]
Ahh, rereading your question:

> Not quite sure what this task should be checking to maintain feature parity. Perhaps if a fulfillmentService is non-null at ANY location where the product is stocked, then that would disqualify it from "manual" shipping?

I think that's the correct approach

**Comment by tekhaus** [comment]
To be clear, this only affects the task when the option to "Ignore line items not fulfilled manually" is selected. I believe the right approach when that option is selected, will be to loop through fulfillment orders (FOs), checking the assigned location for each, and whether that location has a fulfillment service assigned, and thus should be ignored.

For any FOs that have been created by the merchant (i.e. no fulfillment service assigned), the variants for the resulting line items can all be checked to see if their inventory levels qualify them for the desired tagging outcome.

BUT, there is an [open question](https://shopifypartners.slack.com/archives/CB9K9FDTJ/p1671501981745349) on the proper way to map fulfillment order line items to order line items once the 2023-01 API is released, without using deprecated fields.

After the release, this issue will be re-investigated.
