### ISSUE TITLE
Task Deprecation: Update to use FulfillmentOrderLineItem objects

### ISSUE THREAD

**Issue by mattsodomsky** [lightward/mechanic-tasks#181]
https://tasks.mechanic.dev/auto-fulfill-items-that-dont-require-shipping 

![image](https://user-images.githubusercontent.com/1697187/206288279-4baed0a8-9be2-4953-bf9b-1bffe92df4b7.png)

**Comment by tekhaus** [comment]
The fields needed for this task update will not be available until 2023-01 API release. Will patch after the release.

**Comment by tekhaus** [comment]
Update: Shopify has indicated that they _should_ have a solution in place to alleviate this deprecation by the end of March 2023. In the meantime (and in case that date slips), they have also committed to NOT removing the deprecated lineItem resource until that solution is in place (and likely for a good while afterwards).

Accordingly, the alert for this specific deprecation has been suppressed in the Mechanic interface for the time being.
