### ISSUE TITLE
address deprecations in "Auto-fulfill items that don't require shipping"

### ISSUE THREAD

**Issue by isaacbowen** [lightward/mechanic-tasks#262]
https://tasks.mechanic.dev/auto-fulfill-items-that-dont-require-shipping

<img width="715" alt="Screenshot 2023-07-11 at 3 37 35 PM" src="https://github.com/lightward/mechanic-tasks/assets/302012/1dd96537-b19e-4cb6-8ec4-54fe9b5ee988">

(notes below all describe what's available in 2023-04)

We need that `requiresShipping` field, and it turns out that it's available one level up on `FulfillmentOrderLineItem.requiresShipping`.

`FulfillmentOrderLineItem` doesn't have any references to the original product or variant (which - sigh - I understand but don't love), so I think this task will necessarily have to drop the "Ignore products with this tag" option.

**Comment by isaacbowen** [comment]
internal reference: https://secure.helpscout.net/conversation/2297032362/68809/

**Comment by tekhaus** [comment]
Per https://shopifypartners.slack.com/archives/CB9K9FDTJ/p1674000985691099, Shopify has stated that they will provide a solution for looking up the source line item from the FOLI resource before the lineItem resource is fully deprecated in earl 2024.

They said they would have more info prior to 2023-07 release, but so far they have only added the inventoryItemId to the FOLI, which can get the product/variant details in a roundabout way, BUT that doesn't help with things like line item custom attributes. I'll respond in that thread to see where their collective heads are at for resolving this as it affects quite a few tasks in the library.

**Comment by mattsodomsky** [comment]
Sill getting lots of emails about this, hopefully Shopify provides a path soon :D

**Comment by tekhaus** [comment]
#304 has updated the specific task that opened this PR to work around the deprecation. Since there is no deprecation deadline then I would still like to see what Shopify does (if anything) in the 2024-01 release to rectify this issue before updating all of the other affected tasks in mass.

**Comment by tekhaus** [comment]
**Update**: Checked the 2024-01 API release, and nothing has changed in this regard. No link to the original order line item from the FOLI, but the lineItem resource is still there and no date has been set for deprecation resolution.

Makes one wonder if they will ever fully deprecate this resource. Would be nice to know, because then it could just be permanently suppressed.

**Comment by tekhaus** [comment]
**Update**: 2024-07 API - [a variant (and thus indirectly product) connection has now been added to the FOLI](https://shopify.dev/docs/api/admin-graphql/2024-07/objects/FulfillmentOrderLineItem
). 🎉 

This covers a good deal of the usage found in the Library, but will still require updating of the affected tasks. This might be done in most cases without the extra inventory item query, however a new wrinkle is that there has been some [shifting of variant fields to inventory items as well](https://shopify.dev/changelog/product-variant-field-cleanup), so I'll just have dig in and see what all needs to be updated to stay current.

Also, the only thing not covered now from the line item deprecation aspect is any tasks (public library or custom) that need determinate access to the original line item (typically for line item custom attributes).

**Comment by isaacbowen** [comment]
@tekhaus You are incredible to me. Thank you. :)

**Comment by tekhaus** [comment]
And after a review, the only task that actually was affected in the end was the original linked task that was already mitigated.
