### ISSUE TITLE
"Liquid error (line 199): cannot sort values of incompatible types"

### ISSUE THREAD

**Issue by pipposowlo** [lightward/mechanic-tasks#350]
Tried sorting values by custom metafield. Tried to follow the instruction in the docs.
"using the lookups "metafields", "store", "priority", and "value" will result in a collection sorted by the store.priority metafield value on each product"

steps:
1)I created a new product metafields named product.metafields.store.priority. 
2)I populated the metafield with an index value. 100-200-300 and so on
3) tried using as a Product property lookups "metafields". It results in a "Liquid error (line 199): cannot sort values of incompatible types".  
I tried both "integer" and "single line text types" for the metafield but the error is the same.
If i try "store" or  "priority" or "value" instead of "metafields" the task runs but no sorting happens.

**Comment by tekhaus** [comment]
Hi @pipposowlo ,

I just validated this task again using an Integer metafield type, and was able to have it run and sort without error.

Sorry if the docs are not clearer with the example, but here is the order you should enter the values if you wish to use a product metafield. Give that a try and see if it works for you.

![image](https://github.com/lightward/mechanic-tasks/assets/1009347/97e5e655-6547-4149-8f55-9f373db6e1e1)

Also, for a quicker response to any issues you encounter with task configuration or runs, hop into the [Mechanic Slack](https://learn.mechanic.dev/resources/slack) or send an email to team@usemechanic.com.
