### ISSUE TITLE
Bug in sync variant inventory within a product by pack size

### ISSUE THREAD

**Issue by borncamp** [lightward/mechanic-tasks#364]
Hi, there's a bug in one of the existing tasks. "Sync variant inventory within a product by pack size"

The problem occurs when ordering multiple packs (variants) of the same item.

For example: Suppose I order one 5 pack, one 10 pack, and one 20 pack.

What I'd expect to happen is the inventory tag to be updated once subtracting 35 from the old inventory level.

However, what happens instead, three tags are added one subtracting 5, one subtracting 10, and one subtracting 20.

Any chance this bug can get fixed?

**Comment by tekhaus** [comment]
Hi @borncamp , thank you for reporting this issue. We'll get this patched up soon.
