### ISSUE TITLE
Breaking change: Unification of count fields

### ISSUE THREAD

**Issue by mattsodomsky** [lightward/mechanic-tasks#381]
https://shopify.dev/changelog/unification-of-count-fields

We had a merchant right in about this task no longer working: https://tasks.mechanic.dev/email-customers-a-unique-discount-code-two-weeks-after-order-fulfillment

It turns out it's because:

`DiscountCodeBasic.codeCount --> DiscountCodeBasic.codesCount`

“This task needs to be patched along with any others affected by the unification of count fields: https://shopify.dev/changelog/unification-of-count-fields”

** We didn't get deprecation warnings for this, we only found when the task stopped working.

**Comment by mattsodomsky** [comment]
There might be more to this, investigating further

@tekhaus when I use GraphiQL I can't trigger the same thing, and what I am seeing doesn't match the docs - https://shopify.dev/docs/api/admin-graphql/unstable/objects/DiscountCodeBasic

Let me know what you are seeing on your end

**Comment by tekhaus** [comment]
I checked the entire library against the list in the change log as well, and only 2 tasks (patched in #382) were using count fields affected by the unification.
