### ISSUE TITLE
"Set product templates based on product tags" event preview

### ISSUE THREAD

**Issue by isaacbowen** [lightward/mechanic-tasks#387]
https://github.com/lightward/mechanic-tasks/tree/main/docs/set-product-templates-based-on-product-tags

The event preview doesn't render a mutation when the first `tag => template suffix` mapping has a blank value.

Ran into this when a merchant was working to *clear* template suffix values from all of their products.

![2024-08-02 16 10 33](https://github.com/user-attachments/assets/7991388d-2dfa-49ce-af6d-71031bd75ac6)

I moved the mechanic/user/trigger subscription to the end, to explain the order of the event previews in this recording. ;)

**Comment by isaacbowen** [comment]
@tekhaus, can you take this? (I think it is? May I just assign issues like this to you when they come up? Important to me to not assume this stuff!)

**Comment by tekhaus** [comment]
@isaacbowen Yep, no problem, and you can certainly assign them to me going forward. :)
