### ISSUE TITLE
Incomplete docs for "Auto-tag orders that contain an out of stock item"

### ISSUE THREAD

**Issue by isaacbowen** [lightward/mechanic-tasks#395]
https://tasks.mechanic.dev/auto-tag-orders-that-contain-an-out-of-stock-item

It's unclear that the inventory policy is relevant, from the task documentation. Can y'all add a note about that "DENY" requirement, so as to explain to merchants why a "CONTINUE" policy results in the task ignoring the line item? Or might this purpose be better served by making the policy bit configurable?

**Comment by tekhaus** [comment]
I'll make this configurable, per the discussion in #236
