### ISSUE TITLE
"Move out-of-stock products to the end of a collection" - inner loop clobbers `result` from outer loop

### ISSUE THREAD

**Issue by isaacbowen** [lightward/mechanic-tasks#401]
There's a bit in this task where we're traversing _two_ graphql pagination loops at once. Both loops are currently using the variable `result` to store the graphql query results, which breaks pagination for the outer loop.

https://github.com/lightward/mechanic-tasks/blob/b5bf9cb2f2e76c63831652cd60bdcc8ab8f10396/docs/move-out-of-stock-products-to-the-end-of-a-collection/script.liquid#L296-L328

**Comment by tekhaus** [comment]
Good catch, and a good reminder to there will likely be more loops in loops constructs in tasks as the 2K variants support approaches.
