### ISSUE TITLE
Refactor "Delete the oldest x products from a specific collection" for GraphQL

### ISSUE THREAD

**Issue by isaacbowen** [lightward/mechanic-tasks#421]
https://tasks.mechanic.dev/delete-the-oldest-x-products-from-a-specific-collection

**Comment by isaacbowen** [comment]
@tekhaus Do you have space for this one?

**Comment by tekhaus** [comment]
Will be in my next REST update batch, coming soon! :)

**Comment by isaacbowen** [comment]
yay! thank you! 🥳

**Comment by tekhaus** [comment]
Shipped in #422
